-- SecurityAgent — Database Schema

-- Events table
CREATE TABLE IF NOT EXISTS events (
    event_id UUID PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    camera_id TEXT,
    event_type TEXT NOT NULL,
    severity INTEGER NOT NULL DEFAULT 0,
    persons_involved JSONB DEFAULT '[]',
    description TEXT DEFAULT '',
    snapshot_path TEXT,
    audio_clip_path TEXT,
    payload JSONB DEFAULT '{}',
    actions_taken JSONB DEFAULT '[]',
    llm_summary TEXT,
    anomaly_score REAL DEFAULT 0.0,
    consolidated BOOLEAN DEFAULT FALSE
);

CREATE INDEX idx_events_timestamp ON events (timestamp DESC);
CREATE INDEX idx_events_type ON events (event_type);
CREATE INDEX idx_events_camera ON events (camera_id);
CREATE INDEX idx_events_severity ON events (severity);

-- Persons table
CREATE TABLE IF NOT EXISTS persons (
    person_id TEXT PRIMARY KEY,
    name TEXT,
    category TEXT NOT NULL DEFAULT 'unknown',
    face_embedding_count INTEGER DEFAULT 0,
    voice_embedding_count INTEGER DEFAULT 0,
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    total_visits INTEGER DEFAULT 0,
    avg_visit_duration REAL DEFAULT 0.0,
    common_hours JSONB DEFAULT '[]',
    common_days JSONB DEFAULT '[]',
    common_entrances JSONB DEFAULT '[]',
    importance REAL DEFAULT 0.5,
    threat_score REAL DEFAULT 0.0,
    tags JSONB DEFAULT '[]',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_persons_category ON persons (category);
CREATE INDEX idx_persons_last_seen ON persons (last_seen DESC);
CREATE INDEX idx_persons_name ON persons (name);

-- Person sightings (visits log)
CREATE TABLE IF NOT EXISTS person_sightings (
    id SERIAL PRIMARY KEY,
    person_id TEXT REFERENCES persons(person_id),
    camera_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confidence REAL,
    snapshot_path TEXT
);

CREATE INDEX idx_sightings_person ON person_sightings (person_id, timestamp DESC);
CREATE INDEX idx_sightings_camera ON person_sightings (camera_id, timestamp DESC);

-- Daily summaries (generated by LLM)
CREATE TABLE IF NOT EXISTS daily_summaries (
    date DATE PRIMARY KEY,
    summary TEXT NOT NULL,
    event_count INTEGER DEFAULT 0,
    person_count INTEGER DEFAULT 0,
    anomaly_count INTEGER DEFAULT 0,
    generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Configuration log (audit)
CREATE TABLE IF NOT EXISTS config_changes (
    id SERIAL PRIMARY KEY,
    changed_by TEXT DEFAULT 'system',
    config_key TEXT NOT NULL,
    old_value JSONB,
    new_value JSONB,
    changed_at TIMESTAMPTZ DEFAULT NOW()
);
