-- SecurityAgent — Database Schema

-- Events table
CREATE TABLE IF NOT EXISTS events (
    event_id UUID PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    camera_id TEXT,
    event_type TEXT NOT NULL,
    severity INTEGER NOT NULL DEFAULT 0,
    persons_involved JSONB DEFAULT '[]',
    description TEXT DEFAULT '',
    snapshot_path TEXT,
    audio_clip_path TEXT,
    payload JSONB DEFAULT '{}',
    actions_taken JSONB DEFAULT '[]',
    llm_summary TEXT,
    anomaly_score REAL DEFAULT 0.0,
    consolidated BOOLEAN DEFAULT FALSE
);

CREATE INDEX idx_events_timestamp ON events (timestamp DESC);
CREATE INDEX idx_events_type ON events (event_type);
CREATE INDEX idx_events_camera ON events (camera_id);
CREATE INDEX idx_events_severity ON events (severity);

-- Persons table
CREATE TABLE IF NOT EXISTS persons (
    person_id TEXT PRIMARY KEY,
    name TEXT,
    category TEXT NOT NULL DEFAULT 'unknown',
    face_embedding_count INTEGER DEFAULT 0,
    voice_embedding_count INTEGER DEFAULT 0,
    first_seen TIMESTAMPTZ,
    last_seen TIMESTAMPTZ,
    total_visits INTEGER DEFAULT 0,
    avg_visit_duration REAL DEFAULT 0.0,
    common_hours JSONB DEFAULT '[]',
    common_days JSONB DEFAULT '[]',
    common_entrances JSONB DEFAULT '[]',
    importance REAL DEFAULT 0.5,
    threat_score REAL DEFAULT 0.0,
    tags JSONB DEFAULT '[]',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_persons_category ON persons (category);
CREATE INDEX idx_persons_last_seen ON persons (last_seen DESC);
CREATE INDEX idx_persons_name ON persons (name);

-- Person sightings (visits log)
CREATE TABLE IF NOT EXISTS person_sightings (
    id SERIAL PRIMARY KEY,
    person_id TEXT REFERENCES persons(person_id),
    camera_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    confidence REAL,
    snapshot_path TEXT
);

CREATE INDEX idx_sightings_person ON person_sightings (person_id, timestamp DESC);
CREATE INDEX idx_sightings_camera ON person_sightings (camera_id, timestamp DESC);

-- Daily summaries (generated by LLM)
CREATE TABLE IF NOT EXISTS daily_summaries (
    date DATE PRIMARY KEY,
    summary TEXT NOT NULL,
    event_count INTEGER DEFAULT 0,
    person_count INTEGER DEFAULT 0,
    anomaly_count INTEGER DEFAULT 0,
    generated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Configuration log (audit)
CREATE TABLE IF NOT EXISTS config_changes (
    id SERIAL PRIMARY KEY,
    changed_by TEXT DEFAULT 'system',
    config_key TEXT NOT NULL,
    old_value JSONB,
    new_value JSONB,
    changed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Knowledge Graph (Issue #1 — Memória Persistente)
CREATE TABLE IF NOT EXISTS kg_nodes (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL,
    label TEXT NOT NULL,
    properties TEXT DEFAULT '{}',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kg_edges (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    from_node TEXT NOT NULL,
    to_node TEXT NOT NULL,
    type TEXT NOT NULL,
    properties TEXT DEFAULT '{}',
    created_at TEXT NOT NULL,
    FOREIGN KEY (from_node) REFERENCES kg_nodes(id),
    FOREIGN KEY (to_node) REFERENCES kg_nodes(id)
);

CREATE INDEX IF NOT EXISTS idx_kg_edges_from ON kg_edges(from_node);
CREATE INDEX IF NOT EXISTS idx_kg_edges_to ON kg_edges(to_node);
CREATE INDEX IF NOT EXISTS idx_kg_edges_type ON kg_edges(type);

-- Routine Profiles (Issue #1)
CREATE TABLE IF NOT EXISTS routine_profiles (
    entity_id TEXT PRIMARY KEY,
    entity_type TEXT NOT NULL,
    hourly_activity TEXT NOT NULL DEFAULT '[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]',
    daily_activity TEXT NOT NULL DEFAULT '[0,0,0,0,0,0,0]',
    typical_events TEXT DEFAULT '{}',
    total_observations INTEGER DEFAULT 0,
    days_of_data INTEGER DEFAULT 0,
    last_updated TEXT
);

-- Scene Contexts (Issue #1)
CREATE TABLE IF NOT EXISTS scene_contexts (
    camera_id TEXT PRIMARY KEY,
    label TEXT,
    description TEXT DEFAULT '',
    location TEXT NOT NULL DEFAULT 'EXTERNAL',
    environment TEXT DEFAULT '{}',
    known_residents TEXT DEFAULT '[]',
    known_vehicles TEXT DEFAULT '[]',
    zones TEXT DEFAULT '[]',
    routines TEXT DEFAULT '[]',
    last_updated TEXT NOT NULL,
    version INTEGER DEFAULT 1
);

-- Hypotheses (Issue #1)
CREATE TABLE IF NOT EXISTS hypotheses (
    hypothesis_id TEXT PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    description TEXT DEFAULT '',
    probability REAL DEFAULT 0.5,
    status TEXT NOT NULL DEFAULT 'draft',
    supporting_evidence TEXT DEFAULT '[]',
    contradicting_evidence TEXT DEFAULT '[]',
    related_entities TEXT DEFAULT '[]',
    created_at TEXT NOT NULL,
    tested_at TEXT,
    resolved_at TEXT,
    user_feedback TEXT
);

CREATE INDEX IF NOT EXISTS idx_hypotheses_status ON hypotheses(status);
CREATE INDEX IF NOT EXISTS idx_hypotheses_created ON hypotheses(created_at);

-- Conversation History (Issue #1)
CREATE TABLE IF NOT EXISTS conversation_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question_id TEXT NOT NULL,
    text TEXT NOT NULL,
    answer TEXT NOT NULL,
    asked_at TEXT NOT NULL,
    answered_at TEXT,
    priority TEXT DEFAULT 'medium',
    related_entities TEXT DEFAULT '[]',
    related_event_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_conv_ts ON conversation_history(asked_at DESC);
