flowchart TB
    subgraph DC["docker-compose.yml"]
        API_COMPOSE["services.api<br/>build: .<br/>ports: 3000:3000<br/>env: DB_HOST, DB_USER...<br/>depends_on: db"]
        DB_COMPOSE["services.db<br/>image: postgres:16-alpine<br/>volumes: pgdata:/var/lib/...<br/>ports: 5432:5432"]
    end
    subgraph K8S["Manifests Kubernetes"]
        CM["api-configmap.yaml<br/>DB_HOST, DB_PORT..."]
        SEC["api-secret.yaml<br/>DB_USER, DB_PASSWORD..."]
        DAPI["api-deployment.yaml<br/>replicas: 3<br/>+ liveness, readiness"]
        SAPI["api-service.yaml<br/>type: NodePort<br/>porta 30080"]
        PVC["db-pvc.yaml<br/>1Gi persistente"]
        DDB["db-deployment.yaml<br/>imagem: postgres:16<br/>env inline"]
        SDB["db-service.yaml<br/>type: ClusterIP<br/>DNS: db-service:5432"]
    end
    API_COMPOSE --> CM & SEC & DAPI & SAPI
    DB_COMPOSE --> PVC & DDB & SDB
