flowchart LR
    A[Single Host] --> B[API + DB]
    C[Cluster] --> D[Manager]
    C --> E[Worker 1]
    C --> F[Worker 2]
    C --> G[Worker 3]
    D --> H[API réplica 1]
    E --> I[API réplica 2]
    F --> J[API réplica 3]
    G --> K[(DB)]
